name: Make Release

on:
  repository_dispatch:
    types: [tag-added]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build Release Binaries
        run: cargo build --release

      - uses: actions/upload-artifact@v7
        with:
          name: litterbox
          path: target/release/litterbox

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: litterbox

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: litterbox
          name: ${{ github.event.client_payload.version }}
          tag_name: ${{ github.event.client_payload.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
