name: Publish Website
permissions:
  contents: read

on:
  push:
    branches: ["main"]
    paths:
      - README.md
      - website/**
      - .github/workflows/publish-website.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0

      - name: Build Zola site
        run: cd website && zola build

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: website
          packageManager: pnpm
